<a href="https://colab.research.google.com/github/anandhari911/superstore-sales-analysis/blob/main/super_store.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/superstore_sales_10000_rows_cleaned.csv')
df.head()

,Order ID,Date,Product,Category,Region,Quantity,Price,Discount,Customer ID,Sales
0,ORD00001,2024-09-27,Laptop,Technology,West,11,93629.01,0.20,CUST1639,823935.29
1,ORD00002,2024-11-26,Paper,Office Supplies,East,11,2605.22,0.15,CUST0872,24358.81
2,ORD00003,2024-11-04,Bookshelf,Furniture,South,2,18188.97,0.25,CUST0806,27283.46
3,ORD00004,2024-10-03,Desk,Furniture,West,1,7953.93,0.25,CUST0253,5965.45
4,ORD00005,2025-07-14,Tablet,Technology,North,10,5885.88,0.15,CUST0976,50029.98

In [ ]:
df["Revenue"]=df["Quantity"]*df["Price"]*(1-df["Discount"])

In [ ]:
total_revenue=df["Revenue"].sum()
print(total_revenue)

2363337833.17

In [ ]:
df["Cost"]=df["Revenue"]*0.70
df["Profit"]=df["Revenue"]-df["Cost"]

In [ ]:
df.head()

,Order ID,Date,Product,Category,Region,Quantity,Price,Discount,Customer ID,Sales,Revenue,Cost,Profit
0,ORD00001,2024-09-27,Laptop,Technology,West,11,93629.01,0.20,CUST1639,823935.29,823935.2880,576754.70160,247180.58640
1,ORD00002,2024-11-26,Paper,Office Supplies,East,11,2605.22,0.15,CUST0872,24358.81,24358.8070,17051.16490,7307.64210
2,ORD00003,2024-11-04,Bookshelf,Furniture,South,2,18188.97,0.25,CUST0806,27283.46,27283.4550,19098.41850,8185.03650
3,ORD00004,2024-10-03,Desk,Furniture,West,1,7953.93,0.25,CUST0253,5965.45,5965.4475,4175.81325,1789.63425
4,ORD00005,2025-07-14,Tablet,Technology,North,10,5885.88,0.15,CUST0976,50029.98,50029.9800,35020.98600,15008.99400

In [ ]:
df["Revenue"]=df["Quantity"]*df["Price"]*(1-df["Discount"])

In [ ]:
df["Cost"]=df["Revenue"]*0.70
df["Profit"]=df["Revenue"]-df["Cost"]

In [ ]:
df["Month"]=df["Date"].dt.to_period("M").astype(str)
monthly_sales=df.groupby("Month")["Revenue"].sum()
df["Monthly_Sales"]=df["Month"].map(monthly_sales)

In [ ]:
monthly_orders=df.groupby("Month")["Order ID"].nunique()
df["Monthly_Orders"]=df["Month"].map(monthly_orders)

In [ ]:
df["AOV"]=df["Monthly_Sales"]/df["Monthly_Orders"]

In [ ]:
mom=monthly_sales.pct_change()*100
df["MoM Sales %"]=df["Month"].map(mom)
df["MoM Sales %"]=df["MoM Sales %"].clip(lower=0)

In [ ]:
df.to_csv('superstore_sales.csv',index=False)

In [ ]:
df.head()

,Order ID,Date,Product,Category,Region,Quantity,Price,Discount,Customer ID,Sales,Revenue,Cost,Profit,Month,Monthly_Sales,Monthly_Orders,AOV,MoM Sales %
0,ORD00001,2024-09-27,Laptop,Technology,West,11,93629.01,0.20,CUST1639,823935.29,823935.2880,576754.70160,247180.58640,2024-09,1.030191e+08,419,245868.896599,0.000000
1,ORD00002,2024-11-26,Paper,Office Supplies,East,11,2605.22,0.15,CUST0872,24358.81,24358.8070,17051.16490,7307.64210,2024-11,1.074176e+08,425,252747.339980,11.721982
2,ORD00003,2024-11-04,Bookshelf,Furniture,South,2,18188.97,0.25,CUST0806,27283.46,27283.4550,19098.41850,8185.03650,2024-11,1.074176e+08,425,252747.339980,11.721982
3,ORD00004,2024-10-03,Desk,Furniture,West,1,7953.93,0.25,CUST0253,5965.45,5965.4475,4175.81325,1789.63425,2024-10,9.614726e+07,410,234505.500599,0.000000
4,ORD00005,2025-07-14,Tablet,Technology,North,10,5885.88,0.15,CUST0976,50029.98,50029.9800,35020.98600,15008.99400,2025-07,9.513961e+07,393,242085.531322,0.000000

In [ ]:
product_sales=(
    df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)
)
top_5_product=product_sales.head(5)
bottom_5_product=product_sales.tail(5)

In [ ]:
top_5_product.to_csv('top_5_product.csv')

In [ ]:
bottom_5_product.to_csv('bottom_5_product.csv')

In [ ]:
region_by_sales=(df.groupby("Region")["Revenue"].sum().sort_values(ascending=False))
region_by_sales

Region
South    6.031828e+08
West     5.901289e+08
North    5.895287e+08
East     5.804974e+08
Name: Revenue, dtype: float64

In [ ]:
top_5_regions=region_by_sales.head(5)
bottom_5_regions=region_by_sales.tail(5)

In [ ]:
top_5_regions.to_csv('top_5_regions.csv')

In [ ]:
bottom_5_regions.to_csv('bottom_5_regions.csv')

In [ ]:
df["Discount_group"] = pd.cut(df["Discount"], bins=[0, 0.2, 0.4, 0.6, 0.8, 1], labels=["0-20%", "20-40%", "40-60%", "60-80%", "80-100%"])
result = df.groupby("Discount_group", observed=False).agg(
    Sales=("Revenue", "sum"),
    Profit=("Profit", "sum")
).reset_index()
result.to_csv('discount analysis.csv', index=False)
result

  Discount_group         Sales        Profit
0          0-20%  1.564729e+09  4.694188e+08
1         20-40%  3.480448e+08  1.044134e+08
2         40-60%  0.000000e+00  0.000000e+00
3         60-80%  0.000000e+00  0.000000e+00
4        80-100%  0.000000e+00  0.000000e+00